=== JOB INFO ===
IDX=2
GROUP_FILE=/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/results/ranks10/wasserstein_mean_middle.txt
BASENAME=wasserstein_mean_middle
TARGETS(first few)=S0181_2 S0147_2 S0204_2 S0169_2 S0116_1 S0189_2 S0140_1 S0139_2 S0193_1 S0185_2
[PRETRAIN] pretrain_setting exists. Reusing: /home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/model/common_k10/pretrain_setting_wasserstein_mean_middle.pkl
----- RUN: ONLY_TARGET -----
2025-09-20 12:16:38.567590: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:16:38.574473: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:16:38.588665: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1758338198.611495 4085801 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1758338198.617787 4085801 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1758338198.637031 4085801 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338198.637129 4085801 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338198.637132 4085801 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338198.637134 4085801 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-20 12:16:38.642595: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-20 12:16:45,092 - INFO - [RUN] model=RF | domain_mixup=disabled | coral=disabled | vae=disabled | sample_size=None | seed=42 | fold=None | tag=rank_wasserstein_mean_middle | subject_wise_split=disabled | feature_selection=rf | data_leak=disabled
2025-09-20 12:16:45,094 - INFO - Model type: common
2025-09-20 12:16:45,148 - INFO - Loaded: ./data/processed/common/processed_S0181_2.csv
2025-09-20 12:16:45,196 - INFO - Loaded: ./data/processed/common/processed_S0147_2.csv
2025-09-20 12:16:45,241 - INFO - Loaded: ./data/processed/common/processed_S0204_2.csv
2025-09-20 12:16:45,285 - INFO - Loaded: ./data/processed/common/processed_S0169_2.csv
2025-09-20 12:16:45,335 - INFO - Loaded: ./data/processed/common/processed_S0116_1.csv
2025-09-20 12:16:45,383 - INFO - Loaded: ./data/processed/common/processed_S0189_2.csv
2025-09-20 12:16:45,431 - INFO - Loaded: ./data/processed/common/processed_S0140_1.csv
2025-09-20 12:16:45,475 - INFO - Loaded: ./data/processed/common/processed_S0139_2.csv
2025-09-20 12:16:45,521 - INFO - Loaded: ./data/processed/common/processed_S0193_1.csv
2025-09-20 12:16:45,567 - INFO - Loaded: ./data/processed/common/processed_S0185_2.csv
2025-09-20 12:16:45,704 - INFO - [split:subject_time_split|time_stratify=False] global  : n=7691, pos=308, pos_ratio=0.040
2025-09-20 12:16:45,704 - INFO - [split:subject_time_split|time_stratify=False] train   : n=6148, pos=241, pos_ratio=0.039, |Δ|=0.001
2025-09-20 12:16:45,704 - INFO - [split:subject_time_split|time_stratify=False] val     : n=765, pos=34, pos_ratio=0.044, |Δ|=0.004
2025-09-20 12:16:45,704 - INFO - [split:subject_time_split|time_stratify=False] test    : n=778, pos=33, pos_ratio=0.042, |Δ|=0.002
2025-09-20 12:16:45,716 - INFO - y_train unique: [0. 1.], counts: {0.0: 5907, 1.0: 241}
2025-09-20 12:16:52,191 - INFO - Selected features (RF importance): ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
2025-09-20 12:16:52,194 - INFO - Scaler was fit using only X_train (standard procedure).
[I 2025-09-20 12:16:52,203] A new study created in memory with name: no-name-1c8ea0ce-49db-4fa9-8707-2fa48bf51997
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:16:58,773] Trial 0 finished with value: 0.0 and parameters: {'n_estimators': 120, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:05,545] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 134, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:13,377] Trial 2 finished with value: 0.0 and parameters: {'n_estimators': 141, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:24,116] Trial 3 finished with value: 0.0 and parameters: {'n_estimators': 242, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1226    4]
[CV] Fold 0: AUC = 0.5330389875916526
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1227    3]
[CV] Fold 1: AUC = 0.5117562041737169
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1226    4]
[CV] Fold 2: AUC = 0.6084604883443641
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1227    2]
[CV] Fold 3: AUC = 0.5871348433530905
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1224    5]
[CV] Fold 4: AUC = 0.6428168219023426
manual auc_list: [np.float64(0.5330389875916526), np.float64(0.5117562041737169), np.float64(0.6084604883443641), np.float64(0.5871348433530905), np.float64(0.6428168219023426)]
manual auc mean (ignore nan): 0.5766414690730333
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1229    1]
[CV] Fold 0: AUC = 0.5361322617033278
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1229    1]
[CV] Fold 1: AUC = 0.48626974055273553
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1230]
[CV] Fold 2: AUC = 0.6280391919680658
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1229]
[CV] Fold 3: AUC = 0.5901689952018064
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1228    1]
[CV] Fold 4: AUC = 0.6275931414055886
manual auc_list: [np.float64(0.5361322617033278), np.float64(0.48626974055273553), np.float64(0.6280391919680658), np.float64(0.5901689952018064), np.float64(0.6275931414055886)]
manual auc mean (ignore nan): 0.5736406661663048
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1222    8]
[CV] Fold 0: AUC = 0.5211682177100959
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1226    4]
[CV] Fold 1: AUC = 0.5063804286520023
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1227    3]
[CV] Fold 2: AUC = 0.6295080267500734
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1221    8]
[CV] Fold 3: AUC = 0.6047840812870449
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1224    5]
[CV] Fold 4: AUC = 0.6160915890488285
manual auc_list: [np.float64(0.5211682177100959), np.float64(0.5063804286520023), np.float64(0.6295080267500734), np.float64(0.6047840812870449), np.float64(0.6160915890488285)]
manual auc mean (ignore nan): 0.5755864686896089
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1021  209]
[CV] Fold 0: AUC = 0.5220935561195714
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1023  207]
[CV] Fold 1: AUC = 0.5445660603496898
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1064  166]
[CV] Fold 2: AUC = 0.6043650313639427
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1008  221]
[CV] Fold 3: AUC = 0.5849915325994919
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1048  181]
[CV] Fold 4: AUC = 0.5656929156082415
manual auc_list: [np.float64(0.5220935561195714), np.float64(0.5445660603496898), np.float64(0.6043650313639427), np.float64(0.5849915325994919), np.float64(0.5656929156082415)]
manual auc mean (ignore nan): 0.5643418192081875
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1165   65]
[CV] Fold 0: AUC = 0.523970671178793
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1171   59]
[CV] Fold 1: AUC = 0.5215207275803723
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1184   46]
[CV] Fold 2: AUC = 0.584423439147039
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1175   54]
[CV] Fold 3: AUC = 0.5880256844482078
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1166   63]
[CV] Fold 4: AUC = 0.5682331357606548
manual auc_list: Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:30,311] Trial 4 finished with value: 0.0 and parameters: {'n_estimators': 129, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:38,681] Trial 5 finished with value: 0.0 and parameters: {'n_estimators': 155, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:50,155] Trial 6 finished with value: 0.0 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:02,451] Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 244, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:07,969] Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 108, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
[np.float64(0.523970671178793), np.float64(0.5215207275803723), np.float64(0.584423439147039), np.float64(0.5880256844482078), np.float64(0.5682331357606548)]
manual auc mean (ignore nan): 0.5572347316230134
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1225    5]
[CV] Fold 0: AUC = 0.5286061759729271
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1226    4]
[CV] Fold 1: AUC = 0.5199520586576425
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1227    3]
[CV] Fold 2: AUC = 0.6160465879832034
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1228    1]
[CV] Fold 3: AUC = 0.5896838837143663
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1224    5]
[CV] Fold 4: AUC = 0.6433107535986452
manual auc_list: [np.float64(0.5286061759729271), np.float64(0.5199520586576425), np.float64(0.6160465879832034), np.float64(0.5896838837143663), np.float64(0.6433107535986452)]
manual auc mean (ignore nan): 0.5795198919853568
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1119  111]
[CV] Fold 0: AUC = 0.5095794557247603
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1144   86]
[CV] Fold 1: AUC = 0.5310737450648618
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1157   73]
[CV] Fold 2: AUC = 0.6030344398555357
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1137   92]
[CV] Fold 3: AUC = 0.5890311882585381
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1124  105]
[CV] Fold 4: AUC = 0.5789408693197854
manual auc_list: [np.float64(0.5095794557247603), np.float64(0.5310737450648618), np.float64(0.6030344398555357), np.float64(0.5890311882585381), np.float64(0.5789408693197854)]
manual auc mean (ignore nan): 0.5623319396446962
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1229    1]
[CV] Fold 0: AUC = 0.5251868302312465
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1230]
[CV] Fold 1: AUC = 0.5008460236886633
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1230]
[CV] Fold 2: AUC = 0.6247040729924485
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1229]
[CV] Fold 3: AUC = 0.6002152130962461
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1228    1]
[CV] Fold 4: AUC = 0.6161621507197289
manual auc_list: [np.float64(0.5251868302312465), np.float64(0.5008460236886633), np.float64(0.6247040729924485), np.float64(0.6002152130962461), np.float64(0.6161621507197289)]
manual auc mean (ignore nan): 0.5734228581456666
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1178   52]
[CV] Fold 0: AUC = 0.5193616046249295
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1191   39]
[CV] Fold 1: AUC = 0.5213268471517203
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1192   38]
[CV] Fold 2: AUC = 0.6090134614387669
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1176   53]
[CV] Fold 3: AUC = 0.583880186282811
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1167   62]
[CV] Fold 4: AUC = 0.5742661586226362
manual auc_list: [np.float64(0.5193616046249295), np.float64(0.5213268471517203), np.float64(0.6090134614387669), np.float64(0.583880186282811), np.float64(0.5742661586226362)]
manual auc mean (ignore nan): 0.5615696516241727
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1182   48]
[CV] Fold 0: AUC = 0.5231334602368867
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1202   28]
[CV] Fold 1: AUC = 0.519599548787366
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1200   30]
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:19,066] Trial 9 finished with value: 0.0 and parameters: {'n_estimators': 211, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
2025-09-20 12:18:19,067 - INFO - Best hyperparameters: {'n_estimators': 120, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 5}
2025-09-20 12:18:19,067 - INFO - Selected features (from input): ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
2025-09-20 12:18:20,282 - INFO - Saving RF with 3 features.
2025-09-20 12:18:20,358 - INFO - [TRAIN_ONLY] Saved model, features, scaler -> _only_target_rank_wasserstein_mean_middle. Skipping evaluation.
[CV] Fold 2: AUC = 0.5958630700374986
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1191   38]
[CV] Fold 3: AUC = 0.5871436635619531
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1189   40]
[CV] Fold 4: AUC = 0.5757479537115439
manual auc_list: [np.float64(0.5231334602368867), np.float64(0.519599548787366), np.float64(0.5958630700374986), np.float64(0.5871436635619531), np.float64(0.5757479537115439)]
manual auc mean (ignore nan): 0.5602975392670496
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
----- RUN: ONLY_TARGET -----
2025-09-20 12:18:25.003960: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:18:25.008503: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:18:25.020081: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1758338305.038371 4085958 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1758338305.043909 4085958 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1758338305.059224 4085958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338305.059247 4085958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338305.059250 4085958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338305.059252 4085958 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-20 12:18:25.063771: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-20 12:18:28,700 - INFO - [RUN] model=RF | domain_mixup=disabled | coral=disabled | vae=disabled | sample_size=None | seed=42 | fold=None | tag=rank_wasserstein_mean_middle | subject_wise_split=disabled | feature_selection=rf | data_leak=disabled
2025-09-20 12:18:28,701 - INFO - Model type: common
2025-09-20 12:18:28,731 - INFO - Loaded: ./data/processed/common/processed_S0181_2.csv
2025-09-20 12:18:28,755 - INFO - Loaded: ./data/processed/common/processed_S0147_2.csv
2025-09-20 12:18:28,779 - INFO - Loaded: ./data/processed/common/processed_S0204_2.csv
2025-09-20 12:18:28,801 - INFO - Loaded: ./data/processed/common/processed_S0169_2.csv
2025-09-20 12:18:28,827 - INFO - Loaded: ./data/processed/common/processed_S0116_1.csv
2025-09-20 12:18:28,851 - INFO - Loaded: ./data/processed/common/processed_S0189_2.csv
2025-09-20 12:18:28,879 - INFO - Loaded: ./data/processed/common/processed_S0140_1.csv
2025-09-20 12:18:28,902 - INFO - Loaded: ./data/processed/common/processed_S0139_2.csv
2025-09-20 12:18:28,925 - INFO - Loaded: ./data/processed/common/processed_S0193_1.csv
2025-09-20 12:18:28,950 - INFO - Loaded: ./data/processed/common/processed_S0185_2.csv
2025-09-20 12:18:29,004 - INFO - [split:subject_time_split|time_stratify=False] global  : n=7691, pos=308, pos_ratio=0.040
2025-09-20 12:18:29,004 - INFO - [split:subject_time_split|time_stratify=False] train   : n=6148, pos=241, pos_ratio=0.039, |Δ|=0.001
2025-09-20 12:18:29,004 - INFO - [split:subject_time_split|time_stratify=False] val     : n=765, pos=34, pos_ratio=0.044, |Δ|=0.004
2025-09-20 12:18:29,005 - INFO - [split:subject_time_split|time_stratify=False] test    : n=778, pos=33, pos_ratio=0.042, |Δ|=0.002
2025-09-20 12:18:29,009 - INFO - y_train unique: [0. 1.], counts: {0.0: 5907, 1.0: 241}
2025-09-20 12:18:35,116 - INFO - Selected features (RF importance): ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
2025-09-20 12:18:35,119 - INFO - Scaler was fit using only X_train (standard procedure).
[I 2025-09-20 12:18:35,123] A new study created in memory with name: no-name-f6b32ea9-a7bf-4ad4-9353-65428bc57bda
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:39,507] Trial 0 finished with value: 0.0 and parameters: {'n_estimators': 111, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:51,687] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 286, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:06,572] Trial 2 finished with value: 0.0 and parameters: {'n_estimators': 290, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:12,962] Trial 3 finished with value: 0.0 and parameters: {'n_estimators': 117, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1169   61]
[CV] Fold 0: AUC = 0.5224989424703892
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1175   55]
[CV] Fold 1: AUC = 0.5165503384094755
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1187   43]
[CV] Fold 2: AUC = 0.5919490573536781
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1162   67]
[CV] Fold 3: AUC = 0.5990685859441152
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1174   55]
[CV] Fold 4: AUC = 0.5727314422805532
manual auc_list: [np.float64(0.5224989424703892), np.float64(0.5165503384094755), np.float64(0.5919490573536781), np.float64(0.5990685859441152), np.float64(0.5727314422805532)]
manual auc mean (ignore nan): 0.5605596732916422
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1201   29]
[CV] Fold 0: AUC = 0.5250898900169204
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1207   23]
[CV] Fold 1: AUC = 0.5231775239706712
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1213   17]
[CV] Fold 2: AUC = 0.5979712799599095
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1206   23]
[CV] Fold 3: AUC = 0.58751411233418
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1203   26]
[CV] Fold 4: AUC = 0.5905306237651707
manual auc_list: [np.float64(0.5250898900169204), np.float64(0.5231775239706712), np.float64(0.5979712799599095), np.float64(0.58751411233418), np.float64(0.5905306237651707)]
manual auc mean (ignore nan): 0.5648566860093704
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1223    7]
[CV] Fold 0: AUC = 0.5334708121827412
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1226    4]
[CV] Fold 1: AUC = 0.5243936830231246
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1226    4]
[CV] Fold 2: AUC = 0.6180683958596139
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1223    6]
[CV] Fold 3: AUC = 0.5877787186000565
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1225    4]
[CV] Fold 4: AUC = 0.6179614733276884
manual auc_list: [np.float64(0.5334708121827412), np.float64(0.5243936830231246), np.float64(0.6180683958596139), np.float64(0.5877787186000565), np.float64(0.6179614733276884)]
manual auc mean (ignore nan): 0.5763346165986449
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1224    6]
[CV] Fold 0: AUC = 0.5486022983643543
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1229    1]
[CV] Fold 1: AUC = 0.5034722222222222
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1226    4]
[CV] Fold 2: AUC = 0.6064646010817536
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1224    5]
[CV] Fold 3: AUC = 0.5883696725938471
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1226    3]
[CV] Fold 4: AUC = 0.6149273214789726
manual auc_list: [np.float64(0.5486022983643543), np.float64(0.5034722222222222), np.float64(0.6064646010817536), np.float64(0.5883696725938471), np.float64(0.6149273214789726)]
manual auc mean (ignore nan): 0.57236722314823
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1228    2]
[CV] Fold 0: AUC = 0.5496422024816695
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1229    1]
[CV] Fold 1: AUC = 0.5135980682459108
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1230]
[CV] Fold 2: AUC = 0.6131261988283884
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1229]
[CV] Fold 3: AUC = 0.5928415184871578
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1226    3]
[CV] Fold 4: AUC = 0.6321796500141124
manual auc_list: Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:21,072] Trial 4 finished with value: 0.0 and parameters: {'n_estimators': 140, 'max_depth': 29, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:35,538] Trial 5 finished with value: 0.0 and parameters: {'n_estimators': 239, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:48,994] Trial 6 finished with value: 0.0 and parameters: {'n_estimators': 263, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:58,004] Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 193, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:20:05,779] Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 171, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.0.
[np.float64(0.5496422024816695), np.float64(0.5135980682459108), np.float64(0.6131261988283884), np.float64(0.5928415184871578), np.float64(0.6321796500141124)]
manual auc mean (ignore nan): 0.5802775276114478
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1228    2]
[CV] Fold 0: AUC = 0.5328010434292161
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1228    2]
[CV] Fold 1: AUC = 0.49772631133671746
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1229    1]
[CV] Fold 2: AUC = 0.6286267258808689
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1227    2]
[CV] Fold 3: AUC = 0.5990685859441152
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1226    3]
[CV] Fold 4: AUC = 0.6287221281399944
manual auc_list: [np.float64(0.5328010434292161), np.float64(0.49772631133671746), np.float64(0.6286267258808689), np.float64(0.5990685859441152), np.float64(0.6287221281399944)]
manual auc mean (ignore nan): 0.5773889589461824
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1225    5]
[CV] Fold 0: AUC = 0.5254776508742245
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1227    3]
[CV] Fold 1: AUC = 0.5152989283699944
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1227    3]
[CV] Fold 2: AUC = 0.6110352693151773
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1227    2]
[CV] Fold 3: AUC = 0.583280412080158
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1225    4]
[CV] Fold 4: AUC = 0.6350197572678521
manual auc_list: [np.float64(0.5254776508742245), np.float64(0.5152989283699944), np.float64(0.6110352693151773), np.float64(0.583280412080158), np.float64(0.6350197572678521)]
manual auc mean (ignore nan): 0.5740224035814813
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1227    3]
[CV] Fold 0: AUC = 0.529698956570784
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1227    3]
[CV] Fold 1: AUC = 0.505728285391991
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1230]
[CV] Fold 2: AUC = 0.630389327619278
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1224    5]
[CV] Fold 3: AUC = 0.6056131809201242
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1225    4]
[CV] Fold 4: AUC = 0.6287574089754445
manual auc_list: [np.float64(0.529698956570784), np.float64(0.505728285391991), np.float64(0.630389327619278), np.float64(0.6056131809201242), np.float64(0.6287574089754445)]
manual auc mean (ignore nan): 0.5800374318955244
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1223    7]
[CV] Fold 0: AUC = 0.5337175690919346
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1221    9]
[CV] Fold 1: AUC = 0.5234771573604061
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1225    5]
[CV] Fold 2: AUC = 0.6043131901363424
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1222    7]
[CV] Fold 3: AUC = 0.6082592435788878
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1224    5]
[CV] Fold 4: AUC = 0.5979748800451594
manual auc_list: [np.float64(0.5337175690919346), np.float64(0.5234771573604061), np.float64(0.6043131901363424), np.float64(0.6082592435788878), np.float64(0.5979748800451594)]
manual auc mean (ignore nan): 0.5735484080425459
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6148, 135)
X_train nan: 24 inf: 0
X_train col nan count: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
y_train shape: (6148,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6148, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1182   48], y_pred bincount: [1221    9]
[CV] Fold 0: AUC = 0.5334179357021996
[CV] Fold 1: y_val bincount: [1182   48], y_pred bincount: [1225    5]
[CV] Fold 1: AUC = 0.5196347997743938
[CV] Fold 2: y_val bincount: [1181   49], y_pred bincount: [1226    4]
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:20:18,388] Trial 9 finished with value: 0.0 and parameters: {'n_estimators': 265, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
2025-09-20 12:20:18,389 - INFO - Best hyperparameters: {'n_estimators': 111, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1}
2025-09-20 12:20:18,389 - INFO - Selected features (from input): ['steering_speed_pred_error', 'LongAcc_Median', 'SteeringSpeed_Median']
2025-09-20 12:20:19,177 - INFO - Saving RF with 3 features.
2025-09-20 12:20:19,665 - INFO - [TRAIN_ONLY] Saved model, features, scaler -> _only_target_rank_wasserstein_mean_middle. Skipping evaluation.
[CV] Fold 2: AUC = 0.608080319341962
[CV] Fold 3: y_val bincount: [1181   48], y_pred bincount: [1221    8]
[CV] Fold 3: AUC = 0.5970222974880045
[CV] Fold 4: y_val bincount: [1181   48], y_pred bincount: [1222    7]
[CV] Fold 4: AUC = 0.5965107253739768
manual auc_list: [np.float64(0.5334179357021996), np.float64(0.5196347997743938), np.float64(0.608080319341962), np.float64(0.5970222974880045), np.float64(0.5965107253739768)]
manual auc mean (ignore nan): 0.5709332155361073
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
=== DONE (BASENAME=wasserstein_mean_middle) ===

=================================== RESOURCE INFORMATION ===================================
 Requested Resource:
 mem=128gb,walltime=24:00:00,ncpus=8,place=pack 
 Used Resource: 
 mem=741100kb,walltime=00:03:47,ncpus=8,cpupercent=93,vmem=2155620kb
============================================================================================
