=== JOB INFO ===
IDX=3
GROUP_FILE=/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/results/ranks10/wasserstein_mean_low.txt
BASENAME=wasserstein_mean_low
TARGETS(first few)=S0190_2 S0200_1 S0204_1 S0136_2 S0207_2 S0196_1 S0199_1 S0207_1 S0210_1 S0155_1
[PRETRAIN] pretrain_setting exists. Reusing: /home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/model/common_k10/pretrain_setting_wasserstein_mean_low.pkl
----- RUN: ONLY_TARGET -----
2025-09-20 12:16:42.643215: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:16:43.054949: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:16:43.403860: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1758338203.688180  206804 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1758338203.767351  206804 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1758338204.439943  206804 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338204.440084  206804 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338204.440088  206804 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338204.440090  206804 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-20 12:16:44.509741: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-20 12:16:52,274 - INFO - [RUN] model=RF | domain_mixup=disabled | coral=disabled | vae=disabled | sample_size=None | seed=42 | fold=None | tag=rank_wasserstein_mean_low | subject_wise_split=disabled | feature_selection=rf | data_leak=disabled
2025-09-20 12:16:52,275 - INFO - Model type: common
2025-09-20 12:16:52,319 - INFO - Loaded: ./data/processed/common/processed_S0190_2.csv
2025-09-20 12:16:52,359 - INFO - Loaded: ./data/processed/common/processed_S0200_1.csv
2025-09-20 12:16:52,403 - INFO - Loaded: ./data/processed/common/processed_S0204_1.csv
2025-09-20 12:16:52,442 - INFO - Loaded: ./data/processed/common/processed_S0136_2.csv
2025-09-20 12:16:52,481 - INFO - Loaded: ./data/processed/common/processed_S0207_2.csv
2025-09-20 12:16:52,525 - INFO - Loaded: ./data/processed/common/processed_S0196_1.csv
2025-09-20 12:16:52,566 - INFO - Loaded: ./data/processed/common/processed_S0199_1.csv
2025-09-20 12:16:52,607 - INFO - Loaded: ./data/processed/common/processed_S0207_1.csv
2025-09-20 12:16:52,647 - INFO - Loaded: ./data/processed/common/processed_S0210_1.csv
2025-09-20 12:16:52,687 - INFO - Loaded: ./data/processed/common/processed_S0155_1.csv
2025-09-20 12:16:52,747 - INFO - [split:subject_time_split|time_stratify=False] global  : n=7710, pos=280, pos_ratio=0.036
2025-09-20 12:16:52,747 - INFO - [split:subject_time_split|time_stratify=False] train   : n=6165, pos=226, pos_ratio=0.037, |Δ|=0.000
2025-09-20 12:16:52,747 - INFO - [split:subject_time_split|time_stratify=False] val     : n=767, pos=34, pos_ratio=0.044, |Δ|=0.008
2025-09-20 12:16:52,747 - INFO - [split:subject_time_split|time_stratify=False] test    : n=778, pos=20, pos_ratio=0.026, |Δ|=0.011
2025-09-20 12:16:52,752 - INFO - y_train unique: [0. 1.], counts: {0.0: 5939, 1.0: 226}
2025-09-20 12:16:58,924 - INFO - Selected features (RF importance): ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
2025-09-20 12:16:58,930 - INFO - Scaler was fit using only X_train (standard procedure).
[I 2025-09-20 12:16:58,948] A new study created in memory with name: no-name-9dbf3ebf-7a70-448e-9e4e-b6a47b7344b6
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:08,195] Trial 0 finished with value: 0.0 and parameters: {'n_estimators': 170, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:18,993] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 196, 'max_depth': 21, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:31,804] Trial 2 finished with value: 0.0 and parameters: {'n_estimators': 228, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:38,379] Trial 3 finished with value: 0.0 and parameters: {'n_estimators': 121, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:17:53,926] Trial 4 finished with value: 0.0 and parameters: {'n_estimators': 290, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1230    3]
[CV] Fold 0: AUC = 0.5118967452300787
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1229    4]
[CV] Fold 1: AUC = 0.4946127946127946
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1230    3]
[CV] Fold 2: AUC = 0.4857837635615413
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.4728769173213617
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1226    7]
[CV] Fold 4: AUC = 0.45087176293908643
manual auc_list: [np.float64(0.5118967452300787), np.float64(0.4946127946127946), np.float64(0.4857837635615413), np.float64(0.4728769173213617), np.float64(0.45087176293908643)]
manual auc mean (ignore nan): 0.48320839673297256
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.48333333333333334
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1228    5]
[CV] Fold 1: AUC = 0.4666479610924055
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.47957351290684624
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.4836045641601197
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1229    4]
[CV] Fold 4: AUC = 0.40841910552727007
manual auc_list: [np.float64(0.48333333333333334), np.float64(0.4666479610924055), np.float64(0.47957351290684624), np.float64(0.4836045641601197), np.float64(0.40841910552727007)]
manual auc mean (ignore nan): 0.464315695403995
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 0: AUC = 0.501786382341938
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 1: AUC = 0.46306584362139924
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 2: AUC = 0.4998410026187804
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4783389450056117
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1233]
[CV] Fold 4: AUC = 0.4212025200542104
manual auc_list: [np.float64(0.501786382341938), np.float64(0.46306584362139924), np.float64(0.4998410026187804), np.float64(0.4783389450056117), np.float64(0.4212025200542104)]
manual auc mean (ignore nan): 0.4728469387283879
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.48542835765057984
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 1: AUC = 0.4267863823419379
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.50612607557052
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.486887392442948
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1232    1]
[CV] Fold 4: AUC = 0.43357386176330537
manual auc_list: [np.float64(0.48542835765057984), np.float64(0.4267863823419379), np.float64(0.50612607557052), np.float64(0.486887392442948), np.float64(0.43357386176330537)]
manual auc mean (ignore nan): 0.4677604139538582
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.5457164234942012
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 1: AUC = 0.5022633744855968
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.488047138047138
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.4887205387205388
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1230    3]
[CV] Fold 4: AUC = 0.4479414673455184
manual auc_list: [np.float64(0.5457164234942012), np.float64(0.5022633744855968), np.float64(0.488047138047138), np.float64(0.4887205387205388), np.float64(0.4479414673455184)]
manual auc mean (ignore nan): 0.49453778841859863
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:09,190] Trial 5 finished with value: 0.0 and parameters: {'n_estimators': 276, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:20,365] Trial 6 finished with value: 0.0 and parameters: {'n_estimators': 202, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:31,540] Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 196, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:37,459] Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 122, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:18:46,556] Trial 9 finished with value: 0.0 and parameters: {'n_estimators': 246, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
2025-09-20 12:18:46,557 - INFO - Best hyperparameters: {'n_estimators': 170, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 5}
2025-09-20 12:18:46,557 - INFO - Selected features (from input): ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
2025-09-20 12:18:47,497 - INFO - Saving RF with 3 features.
2025-09-20 12:18:47,570 - INFO - [TRAIN_ONLY] Saved model, features, scaler -> _only_target_rank_wasserstein_mean_low. Skipping evaluation.
['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.4922558922558923
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 1: AUC = 0.4538533482977927
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 2: AUC = 0.4703329592218482
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4761690983913206
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1232    1]
[CV] Fold 4: AUC = 0.417860151642797
manual auc_list: [np.float64(0.4922558922558923), np.float64(0.4538533482977927), np.float64(0.4703329592218482), np.float64(0.4761690983913206), np.float64(0.417860151642797)]
manual auc mean (ignore nan): 0.4620942899619302
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.4710624766180322
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 1: AUC = 0.46201833146277593
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1230    3]
[CV] Fold 2: AUC = 0.48756079311634865
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4856715301159746
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1232    1]
[CV] Fold 4: AUC = 0.43481923739057177
manual auc_list: [np.float64(0.4710624766180322), np.float64(0.46201833146277593), np.float64(0.48756079311634865), np.float64(0.4856715301159746), np.float64(0.43481923739057177)]
manual auc mean (ignore nan): 0.4682264737407406
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.4950523756079312
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 1: AUC = 0.46762065095398436
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.5023943135054245
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4872989150766928
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1233]
[CV] Fold 4: AUC = 0.45054210468481004
manual auc_list: [np.float64(0.4950523756079312), np.float64(0.46762065095398436), np.float64(0.5023943135054245), np.float64(0.4872989150766928), np.float64(0.45054210468481004)]
manual auc mean (ignore nan): 0.48058167196576856
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 0: AUC = 0.5523007856341189
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 1: AUC = 0.5129349046015712
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1226    7]
[CV] Fold 2: AUC = 0.4907968574635242
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.48546576879910214
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1227    6]
[CV] Fold 4: AUC = 0.4590765906010769
manual auc_list: [np.float64(0.5523007856341189), np.float64(0.5129349046015712), np.float64(0.4907968574635242), np.float64(0.48546576879910214), np.float64(0.4590765906010769)]
manual auc mean (ignore nan): 0.5001149814198786
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1131  102]
[CV] Fold 0: AUC = 0.5196408529741864
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1112  121]
[CV] Fold 1: AUC = 0.5453049008604565
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [975 258]
[CV] Fold 2: AUC = 0.49474373363262253
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [997 236]
[CV] Fold 3: AUC = 0.4910400299289189
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1021  212]
[CV] Fold 4: AUC = 0.4755228746199773
manual auc_list: [np.float64(0.5196408529741864), np.float64(0.5453049008604565), np.float64(0.49474373363262253), np.float64(0.4910400299289189), np.float64(0.4755228746199773)]
manual auc mean (ignore nan): 0.5052504784032323
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
----- RUN: ONLY_TARGET -----
2025-09-20 12:18:50.980627: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:18:50.984104: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-20 12:18:50.994553: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1758338331.013059  207012 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1758338331.018463  207012 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1758338331.032463  207012 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338331.032522  207012 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338331.032524  207012 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1758338331.032526  207012 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-20 12:18:51.036824: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-20 12:18:54,277 - INFO - [RUN] model=RF | domain_mixup=disabled | coral=disabled | vae=disabled | sample_size=None | seed=42 | fold=None | tag=rank_wasserstein_mean_low | subject_wise_split=disabled | feature_selection=rf | data_leak=disabled
2025-09-20 12:18:54,278 - INFO - Model type: common
2025-09-20 12:18:54,306 - INFO - Loaded: ./data/processed/common/processed_S0190_2.csv
2025-09-20 12:18:54,331 - INFO - Loaded: ./data/processed/common/processed_S0200_1.csv
2025-09-20 12:18:54,358 - INFO - Loaded: ./data/processed/common/processed_S0204_1.csv
2025-09-20 12:18:54,382 - INFO - Loaded: ./data/processed/common/processed_S0136_2.csv
2025-09-20 12:18:54,407 - INFO - Loaded: ./data/processed/common/processed_S0207_2.csv
2025-09-20 12:18:54,434 - INFO - Loaded: ./data/processed/common/processed_S0196_1.csv
2025-09-20 12:18:54,459 - INFO - Loaded: ./data/processed/common/processed_S0199_1.csv
2025-09-20 12:18:54,485 - INFO - Loaded: ./data/processed/common/processed_S0207_1.csv
2025-09-20 12:18:54,509 - INFO - Loaded: ./data/processed/common/processed_S0210_1.csv
2025-09-20 12:18:54,535 - INFO - Loaded: ./data/processed/common/processed_S0155_1.csv
2025-09-20 12:18:54,585 - INFO - [split:subject_time_split|time_stratify=False] global  : n=7710, pos=280, pos_ratio=0.036
2025-09-20 12:18:54,585 - INFO - [split:subject_time_split|time_stratify=False] train   : n=6165, pos=226, pos_ratio=0.037, |Δ|=0.000
2025-09-20 12:18:54,585 - INFO - [split:subject_time_split|time_stratify=False] val     : n=767, pos=34, pos_ratio=0.044, |Δ|=0.008
2025-09-20 12:18:54,585 - INFO - [split:subject_time_split|time_stratify=False] test    : n=778, pos=20, pos_ratio=0.026, |Δ|=0.011
2025-09-20 12:18:54,590 - INFO - y_train unique: [0. 1.], counts: {0.0: 5939, 1.0: 226}
2025-09-20 12:19:00,505 - INFO - Selected features (RF importance): ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
2025-09-20 12:19:00,508 - INFO - Scaler was fit using only X_train (standard procedure).
[I 2025-09-20 12:19:00,513] A new study created in memory with name: no-name-dcee382e-defc-4c04-9a37-5c6557e1d194
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:09,495] Trial 0 finished with value: 0.0 and parameters: {'n_estimators': 170, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:16,598] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 233, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:29,151] Trial 2 finished with value: 0.0 and parameters: {'n_estimators': 252, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:36,574] Trial 3 finished with value: 0.0 and parameters: {'n_estimators': 146, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:43,583] Trial 4 finished with value: 0.0 and parameters: {'n_estimators': 132, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.48589599700710817
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 1: AUC = 0.438842124953236
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.5070520014964459
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4902169846614291
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1232    1]
[CV] Fold 4: AUC = 0.4487289842862899
manual auc_list: [np.float64(0.48589599700710817), np.float64(0.438842124953236), np.float64(0.5070520014964459), np.float64(0.4902169846614291), np.float64(0.4487289842862899)]
manual auc mean (ignore nan): 0.4741472184809018
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1056  177]
[CV] Fold 0: AUC = 0.52334455667789
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [996 237]
[CV] Fold 1: AUC = 0.5581182192293304
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [862 371]
[CV] Fold 2: AUC = 0.48986157875046765
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [821 412]
[CV] Fold 3: AUC = 0.4981668537224092
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [905 328]
[CV] Fold 4: AUC = 0.4836452877183986
manual auc_list: [np.float64(0.52334455667789), np.float64(0.5581182192293304), np.float64(0.48986157875046765), np.float64(0.4981668537224092), np.float64(0.4836452877183986)]
manual auc mean (ignore nan): 0.5106272992196992
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 0: AUC = 0.521754582865694
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 1: AUC = 0.4918256640478863
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.489038533482978
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.4764683875794987
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1232    1]
[CV] Fold 4: AUC = 0.4425936778872569
manual auc_list: [np.float64(0.521754582865694), np.float64(0.4918256640478863), np.float64(0.489038533482978), np.float64(0.4764683875794987), np.float64(0.4425936778872569)]
manual auc mean (ignore nan): 0.48433616917266287
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 0: AUC = 0.4638047138047138
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1229    4]
[CV] Fold 1: AUC = 0.4535447063224841
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.4872240927796483
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.49444444444444446
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1231    2]
[CV] Fold 4: AUC = 0.41452694040511334
manual auc_list: [np.float64(0.4638047138047138), np.float64(0.4535447063224841), np.float64(0.4872240927796483), np.float64(0.49444444444444446), np.float64(0.41452694040511334)]
manual auc mean (ignore nan): 0.4627089795512808
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.5022633744855967
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 1: AUC = 0.43078937523381966
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.4973812196034417
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4949307893752338
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1231    2]
[CV] Fold 4: AUC = 0.44306069374748175
manual auc_list: [np.float64(0.5022633744855967), np.float64(0.43078937523381966), np.float64(0.4973812196034417), np.float64(0.4949307893752338), np.float64(0.44306069374748175)]
manual auc mean (ignore nan): 0.4736850904891147
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:49,553] Trial 5 finished with value: 0.0 and parameters: {'n_estimators': 111, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:19:58,919] Trial 6 finished with value: 0.0 and parameters: {'n_estimators': 165, 'max_depth': 24, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:20:14,511] Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 290, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:20:19,718] Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 159, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.0.
Traceback (most recent call last):
  File "/home/s2240011/git/ddd/vehicle_based_DDD_comparison/project/src/models/architectures/common.py", line 361, in objective
    score_arr = cross_val_score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 684, in cross_val_score
    cv_results = cross_validate(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 411, in cross_validate
    results = parallel(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    test_scores = _score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 148, in __call__
    raise e
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 140, in __call__
    score = scorer._score(
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/home/s2240011/conda/envs/python310/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'needs_proba'
[I 2025-09-20 12:20:33,235] Trial 9 finished with value: 0.0 and parameters: {'n_estimators': 262, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.0.
2025-09-20 12:20:33,236 - INFO - Best hyperparameters: {'n_estimators': 170, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 3}
2025-09-20 12:20:33,236 - INFO - Selected features (from input): ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
2025-09-20 12:20:34,219 - INFO - Saving RF with 3 features.
2025-09-20 12:20:34,321 - INFO - [TRAIN_ONLY] Saved model, features, scaler -> _only_target_rank_wasserstein_mean_low. Skipping evaluation.
['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.4988215488215488
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1228    5]
[CV] Fold 1: AUC = 0.48656004489337823
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1230    3]
[CV] Fold 2: AUC = 0.48227646838757954
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 3: AUC = 0.4904040404040404
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1230    3]
[CV] Fold 4: AUC = 0.4425936778872569
manual auc_list: [np.float64(0.4988215488215488), np.float64(0.48656004489337823), np.float64(0.48227646838757954), np.float64(0.4904040404040404), np.float64(0.4425936778872569)]
manual auc mean (ignore nan): 0.4801311560787608
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 0: AUC = 0.4621586232697344
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1228    5]
[CV] Fold 1: AUC = 0.45035540591096146
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 2: AUC = 0.48627010849233065
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.49111485222596335
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1230    3]
[CV] Fold 4: AUC = 0.4219259367788725
manual auc_list: [np.float64(0.4621586232697344), np.float64(0.45035540591096146), np.float64(0.48627010849233065), np.float64(0.49111485222596335), np.float64(0.4219259367788725)]
manual auc mean (ignore nan): 0.4623649853355725
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 0: AUC = 0.5552001496445941
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1233]
[CV] Fold 1: AUC = 0.5166292555181443
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1228    5]
[CV] Fold 2: AUC = 0.48737373737373735
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.4714927048260382
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1231    2]
[CV] Fold 4: AUC = 0.4700102560345775
manual auc_list: [np.float64(0.5552001496445941), np.float64(0.5166292555181443), np.float64(0.48737373737373735), np.float64(0.4714927048260382), np.float64(0.4700102560345775)]
manual auc mean (ignore nan): 0.5001412206794182
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1041  192]
[CV] Fold 0: AUC = 0.5186868686868686
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1004  229]
[CV] Fold 1: AUC = 0.5682566404788627
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [875 358]
[CV] Fold 2: AUC = 0.49220912832023944
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [822 411]
[CV] Fold 3: AUC = 0.5059109614665169
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [895 338]
[CV] Fold 4: AUC = 0.4838284311929966
manual auc_list: [np.float64(0.5186868686868686), np.float64(0.5682566404788627), np.float64(0.49220912832023944), np.float64(0.5059109614665169), np.float64(0.4838284311929966)]
manual auc mean (ignore nan): 0.5137784060290969
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
X_train.shape: (6165, 135)
X_train nan: 7 inf: 0
X_train col nan count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
X_train all const col: ['Steering_FreqVar', 'SteeringSpeed_FreqVar', 'Lateral_FreqVar', 'LaneOffset_FreqVar', 'LongAcc_FreqVar']
selected_features: ['LongAcc_Skewness', 'LaneOffset_Kurtosis', 'long_acc_pred_error']
y_train shape: (6165,)
y_train nan: 0 unique: [0. 1.]
X_train[selected_features] shape: (6165, 3)
X_train[selected_features] col nan: [0 0 0]
[CV] Fold 0: y_val bincount: [1188   45], y_pred bincount: [1231    2]
[CV] Fold 0: AUC = 0.5354283576505798
[CV] Fold 1: y_val bincount: [1188   45], y_pred bincount: [1229    4]
[CV] Fold 1: AUC = 0.5096894874672653
[CV] Fold 2: y_val bincount: [1188   45], y_pred bincount: [1227    6]
[CV] Fold 2: AUC = 0.49070332959221846
[CV] Fold 3: y_val bincount: [1188   45], y_pred bincount: [1232    1]
[CV] Fold 3: AUC = 0.48898241676019455
[CV] Fold 4: y_val bincount: [1187   46], y_pred bincount: [1227    6]
[CV] Fold 4: AUC = 0.45365554375297606
manual auc_list: [np.float64(0.5354283576505798), np.float64(0.5096894874672653), np.float64(0.49070332959221846), np.float64(0.48898241676019455), np.float64(0.45365554375297606)]
manual auc mean (ignore nan): 0.49569182704464676
[cross_val_score error] got an unexpected keyword argument 'needs_proba'
=== DONE (BASENAME=wasserstein_mean_low) ===

=================================== RESOURCE INFORMATION ===================================
 Requested Resource:
 mem=128gb,walltime=24:00:00,ncpus=8,place=pack 
 Used Resource: 
 mem=741856kb,walltime=00:04:01,ncpus=8,cpupercent=92,vmem=2156040kb
============================================================================================
